# -*- coding: utf-8 -*-
"""globox_database.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QQ2aKH0wcNcIc7QfbW1Ma6AhGgs8Fe74
"""

import psycopg2
import pandas as pd
def read_query_function(query):
    connection_string='postgres://Test:bQNxVzJL4g6u@ep-noisy-flower-846766-pooler.us-east-2.aws.neon.tech/Globox'
    conn = psycopg2.connect(connection_string)
    data_frame = pd.read_sql_query(query,conn)
    conn.close()
    return data_frame

query1 = '''SELECT
  distinct u.id AS user_id,
  u.country,
  u.gender,
  g.group AS test_group,
  g.device,
 SUM(COALESCE(a.spent, 0)) AS total_spent
 FROM users u
 LEFT JOIN groups g ON u.id = g.uid
 LEFT JOIN activity a ON u.id = a.uid
 GROUP BY u.id, u.country, u.gender, g.group,g.device'''
read_query_function(query1)

query2='''
-- Select users
SELECT *
FROM users

JOIN activity
ON users.id = activity.uid
-- join 'users' and  'groups' with matching user IDs
JOIN groups
ON users.id= groups.uid
'''
read_query_function(query2)

# query 3
query3='''SELECT activity.uid, COUNT(*) AS buy_onces
FROM activity
GROUP BY activity.uid
HAVING COUNT(*) < 2;'''
read_query_function(query3)

# query 4
query4='''SELECT *
FROM users
iNNER JOIN activity
ON users.id = activity.uid;'''
read_query_function(query4)

query5='''SELECT uid, COALESCE(activity.device, 'Unknown') AS device, COALESCE(activity.spent, 0 ) AS spent
FROM Activity;'''
read_query_function(query5)

query6='''SELECT COUNT(DISTINCT uid) AS num_users_in_experiment
FROM activity;'''
read_query_function(query6)

query7='''WITH user_spend AS (
  SELECT
    uid,
    SUM(spent) AS total_spend,
    COUNT(*) as cnt_purchases
  FROM activity
  GROUP BY uid
),

joined AS (
  SELECT
    uid,
    gender,
    country,
    g.group as grp,
    CASE
      WHEN g.group = 'A' THEN 'control'
      WHEN g.group = 'B' THEN 'treatment'
      ELSE 'problem!'
    END AS cluster,
    CASE WHEN cnt_purchases > 0 THEN 1 ELSE 0 END AS converted
  FROM users
  LEFT JOIN groups g ON uid = id
  LEFT JOIN user_spend USING (uid)
)

SELECT
  SUM(converted) * 1.0 / COUNT(*) AS overall_conversion_rate
FROM joined;'''
read_query_function(query7)

query8='''WITH user_spend AS (
  SELECT
    uid,
    SUM(spent) AS total_spend,
    COUNT(*) as cnt_purchases
  FROM activity
  GROUP BY uid
),

joined AS (
  SELECT
    uid,
    gender,
    country,
    g.group as grp,
    CASE
      WHEN g.group = 'A' THEN 'control'
      WHEN g.group = 'B' THEN 'treatment'
      ELSE 'problem!'
    END AS cluster,
    CASE WHEN cnt_purchases > 0 THEN 1 ELSE 0 END AS converted
  FROM users
  LEFT JOIN groups g ON uid = id
  LEFT JOIN user_spend USING (uid)
)

SELECT
  cluster,
  COUNT(*) AS total_users,
  SUM(converted) AS converted_users,
  SUM(converted) * 1.0 / COUNT(*) AS conversion_rate
FROM joined
GROUP BY cluster;
'''
read_query_function(query8)

query9='''WITH user_spend AS (
  SELECT
    uid,
    SUM(spent) AS total_spend,
    COUNT(*) as cnt_purchases
  FROM activity
  GROUP BY uid
),

joined AS (
  SELECT
    uid,gender, country,
    g.group as grp,
    CASE
      WHEN g.group = 'A' THEN 'control'
      WHEN g.group = 'B' THEN 'treatment'
      ELSE 'problem!'
    END AS cluster,
    CASE WHEN cnt_purchases > 0 THEN 1 ELSE 0 END AS converted,
    total_spend
  FROM users
  LEFT JOIN groups g ON uid = id
  LEFT JOIN user_spend USING (uid)
)

SELECT
  cluster,
  AVG(total_spend) AS avg_spend_per_user
FROM joined
GROUP BY cluster;
'''
read_query_function(query9)

query10='''
WITH user_spend AS (
  SELECT
  	uid,
  	SUM(spent) AS total_spend,
		COUNT(*) as cnt_purchases
  FROM activity
  GROUP BY uid
),

joined AS (
  SELECT
    uid,
	  gender,
	  country,
    g.group as grp,
    CASE
  		WHEN g.group = 'A' THEN 'control'
  		WHEN g.group = 'B' THEN 'treatment'
  		ELSE 'problem!'
    END AS cluster,
    CASE WHEN cnt_purchases > 0 THEN 1 ELSE 0 END AS converted
  FROM users
  LEFT JOIN groups g ON uid = id
  LEFT JOIN user_spend USING (uid)
)

select *
from joined
'''
read_query_function(query10)

query11='''
WITH user_spend AS (
  SELECT  uid, SUM(spent) AS total_spend, COUNT(*) as cnt_purchases
  FROM activity
  GROUP BY uid
),
joined AS (
  SELECT
    uid,gender, country,
    g.group as grp,
    CASE
      WHEN g.group = 'A' THEN 'control'
      WHEN g.group = 'B' THEN 'treatment'
      ELSE 'problem!'
    END AS cluster,
    CASE WHEN cnt_purchases > 0 THEN 1 ELSE 0 END AS converted
  FROM users
  LEFT JOIN groups g ON uid = id
  LEFT JOIN user_spend USING (uid)
)

SELECT
  cluster,
  COUNT(*) AS total_users
FROM joined
GROUP BY cluster;
'''
read_query_function(query11)

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(_df_1, *['total_users'], **{})
chart